# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific aliases and functions
if [ -f /opt/rh/python27/enable ]; then
    . /opt/rh/python27/enable
fi
