---
- name: install php 5.6
  yum:
    name: "{{ packages }}"
    state: latest
    enablerepo: remi,remi-php56
  vars:
    packages:
    - php56
    - php56-php-mbstring
    - php56-php-pdo
    - php56-php-mysqlnd
    - php56-php-intl
    - php56-php-bcmath
    - php56-php-soap
    - php56-php-pecl-xdebug
    - php56-php-pecl-memcache
    - php56-php-pecl-memcached
    - php56-php-mcrypt
    - php56-php-fpm
    - php56-php-gd

- name: set access log file
  file:
    state: directory
    path: /var/log/php-fpm
    mode: 0777

- name: php.ini file
  template:
    src: php.ini
    dest: /opt/remi/php56/root/etc/php.ini

- name: custom xdebug configuration .ini file
  template:
    src: xdebug-conf.ini
    dest: /opt/remi/php56/root/etc/php.d/xdebug-conf.ini

- name: www.cnf file
  template:
    src: www.conf
    dest: /opt/remi/php56/root/etc/php-fpm.d/www.conf

- name: create php session directory
  file:
    state: directory
    path: /var/lib/php/session
    mode: 0777

- name: set access log file
  file:
    state: touch
    dest: /var/log/php-fpm/access.log
    mode: 0777
  changed_when: false

- name: set error log file
  file:
    state: touch
    dest: /var/log/php-fpm/error.log
    mode: 0777
  changed_when: false

- name: set slow log file
  file:
    state: touch
    dest: /var/log/php-fpm/slow.log
    mode: 0777
  changed_when: false

- name: start php-fpm
  service:
    name: php56-php-fpm
    state: started
    enabled: true

- name: enable php56
  template:
    src: enablephp56.sh
    dest: /etc/profile.d/enablephp56.sh
